# Generated by Django 4.1.1 on 2022-11-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subCategory',
            new_name='offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
