# Generated by Django 4.1.1 on 2022-11-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_subcategory_product_offer_remove_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
